#VENTANA
ANCHO_VENTANA = 900
ALTO_VENTANA = 500

#CORDENADA DEL PISO
NIVEL_PISO = 552
NIVEL_TECHO = 50

#FOTOGRAMAS POR SEGUNDO
FPS = 120

#RUTA DE IMAGENES
RUTA_IMAGEN = './recursos/'#RUTA DE IMAGENES
PATH_FRAME_UNIT_IMAGE = RUTA_IMAGEN + "interface/Marco.png"

#DIRECCION DONDE MIRA EL PERSONAJKE
IZQUIERDA = -1
DERECHA = 1

#SIZES
SIZE_FRAME_UNITY = (1/28*ANCHO_VENTANA, 1/16*ALTO_VENTANA)
SPACE_BETWEEN_FRAMES = 3 / 70 * ANCHO_VENTANA
SIZE_FONT_TIME = 30
SIZE_TIME = (100, 25)
SIZE_FONT_GOLD = 30
SIZE_GOLD = (100, 25)


#AMOUNTS

AMOUNT_FRAMES_UNITIES = 8

#POSITIONS
POS_FRAME_UNITY = (9/14*ANCHO_VENTANA,9/80*ALTO_VENTANA)
POS_TIME = (2/3*ANCHO_VENTANA,1/50*ALTO_VENTANA)
POS_GOLD = (1/3*ANCHO_VENTANA,1/50*ALTO_VENTANA)


#TAMAÑO DE COLLIDERECT
ALTURA_PIES = 8 # Aprox Gravedad/2 + 1

#MODO DEBUG // DIBUJAR RECTANGULOS
DEBUG = False

#COLORES
RED = (255,0,0)
GREEN = (0,255,0)
BLUE = (0,0,255)
BLACK = (0,0,0)
WHITE = (255,255,255)
YELLOW = (255,255,0)
CYAN = "#d7fcd4"
DORADO = "#b68f40"

#ESTADOS
M_STATE_NORMAL = 1
M_STATE_HOVER = 2
M_STATE_CLICK = 3
M_BRIGHT_HOVER = 1
M_BRIGHT_CLICK = 2

#TILED
PLATAFORMA = "P"
PISO = "O"
MURO = "M"
LOOT = "B"
CAJA = "C"
PINCHO = "S"
FONDO_ACIDO = "A"
TOP_ACIDO = "T"
MOBILE = "U"

CORAZON = RUTA_IMAGEN + r"Menu/Button/Health_Dot.png"
BALA = RUTA_IMAGEN + r"Menu/Button/Armor_Bar_Dot.png"



