#VENTANA
ANCHO_VENTANA = 700
ALTO_VENTANA = 400

#CORDENADA DEL PISO
NIVEL_PISO = 552
NIVEL_TECHO = 50

#FOTOGRAMAS POR SEGUNDO
FPS = 120

#RUTA DE IMAGENES
RUTA_IMAGEN = r"C:\Users\lucia\Documents\Castle Defense\recursos\\"  #RUTA DE IMAGENES
RUTA_MUSICA = r"C:\Users\lucia\Documents\JUEGO_FINAL\sounds\\"   #RUTA DE MUSICA

#DIRECCION DONDE MIRA EL PERSONAJKE
IZQUIERDA = -1
DERECHA = 1

#TAMAÑO DE COLLIDERECT
ALTURA_PIES = 8 # Aprox Gravedad/2 + 1

#MODO DEBUG // DIBUJAR RECTANGULOS
DEBUG = False

#COLORES
RED = (255,0,0)
GREEN = (0,255,0)
BLUE = (0,0,255)
BLACK = (0,0,0)
WHITE = (255,255,255)
YELLOW = (255,255,0)
CYAN = "#d7fcd4"
DORADO = "#b68f40"

#ESTADOS
M_STATE_NORMAL = 1
M_STATE_HOVER = 2
M_STATE_CLICK = 3
M_BRIGHT_HOVER = 1
M_BRIGHT_CLICK = 2

#TILED
PLATAFORMA = "P"
PISO = "O"
MURO = "M"
LOOT = "B"
CAJA = "C"
PINCHO = "S"
FONDO_ACIDO = "A"
TOP_ACIDO = "T"
MOBILE = "U"

CORAZON = RUTA_IMAGEN + r"Menu\Button\Health_Dot.png"
BALA = RUTA_IMAGEN + r"Menu\Button\Armor_Bar_Dot.png"



